apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backstage
  annotations:
    backstage.io/techdocs-ref: dir:.
    github.com/project-slug: M-Sharjeel-Tariq/backstage
spec:
  type: other
  lifecycle: unknown
  owner: guests
